language: java

sudo: required

before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

install:
  - . ./install-jdk.sh -F 11 -L BCL
  - chmod a+x ./gradlew


cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew $GRADLE_BUILD_OPTS -PfindbugsXmlReportEnabled=true --rerun-tasks --full-stacktrace build
