language: java

sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_7900514af20e_key -iv $encrypted_7900514af20e_iv -in secring.base64.gpg.enc -out secring.base64.gpg -d
  - base64 -d secring.base64.gpg > secring.gpg
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

install: 
  - . ./install-jdk.sh -F 10 -L BCL
  - chmod a+x ./gradlew

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=secring.gpg -PnexusUsername=$NEXUS_USER -PnexusPassword=$NEXUS_PASSWORD -Poss-releases.username=$NEXUS_USER -Poss-releases.password=$NEXUS_PASSWORD --recompile-scripts --refresh-dependencies --info --full-stacktrace modularBuild uploadArchives nexusStagingRelease
