language: java

sudo: false

before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
  - sudo apt-get install p7zip-full

install:
  - . ./install-jdk.sh -F 10 -L BCL
  - chmod a+x ./gradlew
  - 7z x secring.zip -p$KEY_RING_PASSWORD


cache:
  directories:
    - $HOME/.gradle

script: ./gradlew -PfindbugsXmlReportEnabled=true -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -PnexusUsername=$NEXUS_USER -PnexusPassword=$NEXUS_PASSWORD -Poss-releases.username=$NEXUS_USER -Poss-releases.password=$NEXUS_PASSWORD --recompile-scripts --refresh-dependencies --info --full-stacktrace uploadArchives nexusStagingRelease
